services:
  - type: web
    name: petstore-backend
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /api/v1/pets?page=0&pageSize=5
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: petstore-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: petstore-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: petstore-postgres
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: petstore-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: petstore-postgres
          property: password
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: CORS_ALLOWED_ORIGINS
        value: https://petstore-frontend.onrender.com

  - type: web
    name: petstore-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://petstore-backend.onrender.com/api/v1

databases:
  - name: petstore-postgres
    plan: free
    databaseName: petstore
    user: petstore
